// Shown on the empty landing screen, under the drop zone: a one-glance explainer
// of what GPXSheet does plus real example output (a Sheet and a Table from the
// same 93-mile Bay Area route, generated by the CLI — see public/guide/).
const BASE = import.meta.env.BASE_URL;

const STEPS = [
  {
    n: "1",
    title: "Drop a GPX",
    body: "Drag a route or track from Basecamp, Scenic, Gaia, onX, inRoute, a Garmin or Zūmo — anything that exports GPX. It's processed on the spot; no account, no sign-in.",
  },
  {
    n: "2",
    title: "Sheet",
    body: "A run of glanceable strips: every turn and road-name change in order, with fuel stops and mileage, sized for a tank-bag window. Export as PDF or PNG.",
  },
  {
    n: "3",
    title: "Table",
    body: "A classic route table — cumulative miles, fuel and lunch markers, and ETAs from your departure time. Copy as Markdown or HTML, or download.",
  },
];

export function IntroGuide() {
  return (
    <section className="mt-10 text-left">
      <h2 className="text-xl font-bold text-slate-800 text-center">
        Turn GPX routes into tank-bag cheat sheets
      </h2>
      <p className="mt-2 text-sm text-slate-500 text-center max-w-2xl mx-auto">
        GPXSheet reads your ride and gives you two print-ready, at-a-glance views of
        it — a map-strip <strong>Sheet</strong> and a route <strong>Table</strong>.
      </p>

      <ol className="mt-8 grid gap-4 sm:grid-cols-3">
        {STEPS.map((s) => (
          <li
            key={s.n}
            className="rounded-xl border border-slate-200 bg-white p-4"
          >
            <span className="flex h-7 w-7 items-center justify-center rounded-full bg-brand text-sm font-bold text-white">
              {s.n}
            </span>
            <h3 className="mt-3 text-sm font-semibold text-slate-800">{s.title}</h3>
            <p className="mt-1 text-xs leading-relaxed text-slate-500">{s.body}</p>
          </li>
        ))}
      </ol>

      <div className="mt-8 grid gap-6 md:grid-cols-2">
        <ExampleCard
          label="Sheet output"
          src={`${BASE}guide/example-sheet.png`}
          alt="Example GPXSheet strip sheet: ordered turns, road-name changes and fuel stops along a route."
        />
        <ExampleCard
          label="Table output"
          src={`${BASE}guide/example-table.png`}
          alt="Example GPXSheet route table: stops with cumulative distance, fuel markers and ETAs."
        />
      </div>
      <p className="mt-3 text-center text-xs text-slate-400">
        Real output from a 93-mile Bay Area route.
      </p>
    </section>
  );
}

function ExampleCard({ label, src, alt }: { label: string; src: string; alt: string }) {
  return (
    <figure className="overflow-hidden rounded-xl border border-slate-200 bg-white">
      <figcaption className="border-b border-slate-100 bg-slate-50 px-3 py-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </figcaption>
      <img src={src} alt={alt} loading="lazy" className="block w-full" />
    </figure>
  );
}
